image: ubuntu

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake g++ pkg-config doxygen libboost-all-dev zlib1g-dev liblzma-dev libcbor-dev
  script:
    - cmake -DBUILD_TESTS=ON .
    - make

test:
  stage: test
  script:
    - ./tests/tests

pages:
  stage: deploy
  script:
    - make doc
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
