image: ubuntu

stages:
  - build_and_test
  - deploy

build_and_test:
  stage: build_and_test
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt -y install cmake g++ pkg-config git doxygen libboost-all-dev zlib1g-dev liblzma-dev
  script:
    - cmake -DBUILD_TESTS=ON .
    - make
    - ./tests/tests

pages:
  stage: deploy
  dependencies:
    - build_and_test
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt -y install cmake g++ pkg-config git doxygen libboost-all-dev zlib1g-dev liblzma-dev
  script:
    - cmake .
    - make doc
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - tags
