image: ubuntu

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt -y install cmake g++ pkg-config git doxygen libboost-all-dev zlib1g-dev liblzma-dev libcbor-dev
  script:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTS=ON ..
    - make
  artifacts:
    paths:
      - ./build

test:
  stage: test
  dependencies:
    - build
  script:
    - ./build/tests/tests

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - make -C build doc
    - mv build/doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
